language: php

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer self-update
  - composer clear-cache
  - composer install --no-interaction

script:
  - composer ci

notifications:
    email: false
